---
title: "2018 Ocean City Rentals"
output: html_document
keep_md: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

Results only include houses with 2-3 bathrooms and 4 bedrooms between $3,000 and $4,400 for the week of July 7th through July 14th.

```{r}
require(tidyverse)
require(rvest)
require(xml2)
require(XML)
require(magrittr)
require(DT)

get_OC_rental_listings <- function(week, year, min_price = 3000, max_price = 3499, date_string = "July 07, 2018 to July 14, 2018") {
  
  url <- paste0("http://www.bergerrealty.com/rental/search.html?week=", week, "&nweek=1&beds=7&bath=4&ulimit=0&minprice=", min_price, "&maxprice=", max_price, "&sortby=1&limit=100&year=", year)
  
  geo <- read_html(url) %>%
    html_nodes(".geo") %>%
    html_text() %>%
    gsub(pattern = date_string, 
        replacement = "") %>%
    data_frame()

  price <- read_html(url) %>%
    html_nodes(".price") %>%
    html_text() %>%
    data_frame() 

  html <- htmlParse(url) %>%
    xpathSApply("//a/@href") %>%
    data_frame()
  colnames(html) <- "urls"
  
  html <- html %>%
    filter(grepl("rental/[0-9]", urls)) %>%
    filter(!grepl("plus", urls)) %>%
    filter(!grepl("facebook", urls)) %>%
    filter(!grepl("twitter", urls)) %>%
    mutate(urls = paste0("http://www.bergerrealty.com", .$urls)) %>%
    mutate(urls = gsub("&beds.*", "", .$urls))
  
  results <- cbind(geo, price) 
  colnames(results) <-  c("address", "price")
  number <- sapply(strsplit(results$address, " "), function(x) x[1])
  street <- sapply(strsplit(results$address, " "), function(x) x[2])
  floor <- sapply(strsplit(results$address, " "), function(x) x[4])
  
  results <- cbind(results, number, street, floor, html)
  
  results$number <- as.integer(as.character(number))
  results$block <- ifelse(nchar(results$number) == 3, substr(results$number, 1,1), substr(results$number, 1,2)) %>%
    as.integer()
  
  results$price <- gsub(x = results$price, pattern = "\\$", replacement = "") %>%
    as.numeric()
  
  results <- results %>%
    select(block, number, street, floor, price, address, urls)
  
  return(results)
}

week_num <- 27
  
year_num <- 2018

results <- get_OC_rental_listings(week = week_num, 
                                  year = year_num, 
                                  min_price = 3000, 
                                  max_price = 3499)

results2 <- get_OC_rental_listings(week = week_num, 
                                  year = year_num, 
                                  min_price = 3500, 
                                  max_price = 3999)

results3 <- get_OC_rental_listings(week = week_num, 
                                  year = year_num, 
                                  min_price = 4000, 
                                  max_price = 4401)

results_all <- rbind(results, results2, results3) %>%
  unique() %>%
  filter(street %in% c("Central", "Wesley", "Asbury")) %>%
  filter(block >= 18) %>%
  mutate(`direction facing` = case_when((.$number %% 2) == 0 ~ "Ocean Side", (.$number %% 2) == 1 ~ "Bay Side")) %>%
  select(block, number, street, floor, price, `direction facing`, address, urls) %>%
  arrange(block, number) 

results_all <- results_all %>%
  mutate('link to listing' = paste0("<a href='", urls, "' target='_blank'>click to view</a>"))

results_all %>%
  select(-urls) %>%
  datatable(filter = "top", options = list(pageLength = 100, autoWidth = FALSE), escape = F)
```